import type { Metadata } from "next";
import {  Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import ThemeProvider from "@/components/theme-provider/page";
import CheckContext from "./context/page";
import { SessionProvider } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cormorantInfant = localFont({
  src: "./fonts/CormorantInfant-Regular.ttf",
  variable: "--font-comorant-infant",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${cormorantInfant.variable} `}
      suppressHydrationWarning
    >
      <body className="antialiased">
        <SessionProvider>
        <CheckContext>

       
        {children}

        <ThemeProvider />
         </CheckContext>
         </SessionProvider>
      </body>
    </html>
  );
}
