
import type { Metadata } from "next"
import localFont from "next/font/local"
import Navbar from "../layouts/navbar/page"


const comorantInfant = localFont({
  src: "../../fonts/CormorantInfant-Regular.ttf",
  variable: "--font-comorant-infant",
})

export const metadata: Metadata = {
  title: "Product Page",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
     
      <div className={`${comorantInfant.variable}`}>
         

       
        <Navbar />
        {children}
        
          
      </div>
    
  )
}